export const INIT_REGISTER = "[USER] INIT_REGISTER";
export const REGISTER_SUCCESS = "[USER] REGISTER_SUCCESS";
export const REGISTER_FAILURE = "[USER] REGISTER_FAILURE";

export const INIT_LOGIN = "[USER] INIT_LOGIN";
export const LOGIN_SUCCESS = "[USER] LOGIN_SUCCESS";
export const LOGIN_FAILURE = "[USER] LOGIN_FAILURE";
